# Build stage
FROM golang:1.20.4-alpine3.18 AS builder
WORKDIR /app
COPY . .

RUN go build -o main cmd/matchreport/main.go

# Run stage
FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/main .
COPY .env .

EXPOSE 8080
CMD [ "/app/main" ]
